# v3/cm3_backend.R
# for building the backend

# Build C++ code
cm_source_backend = function(user_defined = NULL, verbose = NULL)
{
    # Generate user-defined functions
    user_defined_file = paste0(cm_path_, "model_v3/user_defined.cpp");
    new_user_defined = c(
        paste("// Generated by covidm", date()),
        "",
        "#include \"user_defined.h\"",
        "#include \"convenience.h\"",
        "",
        "void CppChanges(const vector<double>& x, Parameters& P)",
        "{",
        "    (void) x; (void) P;",
        paste0("    ", user_defined$model_v3$cpp_changes),
        "}",
        "",
        "double CppLogLikelihood(const vector<double>& x, Parameters& P, Reporter& dyn, double t_min, double t_max)",
        "{",
        "    (void) x; (void) P; (void) dyn; (void) t_min; (void) t_max;",
        "    double ll = 0.0;",
        paste0("    ", user_defined$model_v3$cpp_loglikelihood),
        "    return ll;",
        "}",
        "",
        "bool CppObserver(Parameters& P, Randomizer& R, Reporter& dyn, double t, vector<double>& x, Metapopulation& Mp)",
        "{",
        "    (void) P; (void) R; (void) dyn; (void) t; (void) x; (void) Mp;",
        paste0("    ", user_defined$model_v3$cpp_observer),
        "    return true;",
        "}"
    );

    if (file.exists(user_defined_file)) {    
        existing_user_defined = readLines(user_defined_file);
        if (length(existing_user_defined) != length(new_user_defined) || any(existing_user_defined[-1] != new_user_defined[-1])) {
            writeLines(new_user_defined, user_defined_file);
        }
    } else {
        writeLines(new_user_defined, user_defined_file);
    }

    # Build and import source
    # TODO these commented lines are probably not needed (but check)
    # sourceCpp(paste0(cm_path_, "/model_v1/corona.cpp"), 
    #           rebuild  = cm_force_rebuild_,
    #           cacheDir = cm_build_dir_,
    #           verbose  = cm_build_verbose_)
    # sourceCpp(paste0(cm_path_, "/model_v2/Rcpp_interface.cpp"), 
    #           rebuild  = cm_force_rebuild_,
    #           cacheDir = cm_build_dir_,
    #           verbose  = cm_build_verbose_)
    sourceCpp(paste0(cm_path_, "/model_v3/Rcpp_interface.cpp"), 
              rebuild  = cm_force_rebuild_,
              cacheDir = cm_build_dir_,
              verbose  = ifelse(is.null(verbose), cm_build_verbose_, verbose))
}
